services:
  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    # volumes:
    #   - redis-data-dev:/data
